### ISSUE TITLE
agent version is not "modifyable"

### ISSUE THREAD

**Issue by OckyKristanto-TomTom** [gsoft-inc/ansible-role-azure-devops-agent#34]
**[Description]**
variable ```az_devops_agent_version``` is used to define agent version. However this version can only be used once and consecutive change will not take effect

**[Possible root cause]**
if ```config.sh``` already present in the target node then this step will be skipped. Thus, the version number which embedded inside ```az_devops_agent_package_url``` is ignored. In the end, upgrade/downgrade agent is not doable without manually delete ```config.sh``` in the target node
```
- name: Download and unarchive
  unarchive:
    src: "{{ az_devops_agent_package_url }}"
    dest: "{{ az_devops_agent_folder }}"
    remote_src: yes
    owner: "{{ az_devops_agent_user }}"
    group: "{{ az_devops_agent_user }}"
    creates: "{{ az_devops_agent_folder }}/config.sh"
```
