### ISSUE TITLE
Error when provisioning build agent - Templating type error

### ISSUE THREAD

**Issue by dendle** [gsoft-inc/ansible-role-azure-devops-agent#72]
Hello All,

I get the following error when running this role on ubuntu-focal-20.04.

```
TASK [gsoft.azure_devops_agent : Configure agent as a build server] ************
fatal: [default]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ (agent_cmd_args + build_agent_cmd_args) | join(' ') }}): can only concatenate str (not \"list\") to str"}
```

It appears to be concatenating two lists, which are properly defined - I have no idea whats wrong!

Can anyone help?

Thanks,
Matt

**Comment by thebtm** [comment]
I also get this same error when deploying to RHEL 8.

**Comment by thebtm** [comment]
After doing some debugging, I have noticed that the Set Proxy task is trying to append lists together but for some reason, its converting it to a string. I commented out the Set Proxy tasks and was able to get past the error. Not sure why Ansible is making the string conversion. more toubleshooting will be required to figure out how to fix this but if you don't depend on the proxy step, comment it out on your downloaded tasks.

```Ansible
- name: Set proxy
  set_fact:
    agent_cmd_args: "{{ agent_cmd_args }} + ['--proxyurl \\'{{ az_devops_proxy_url }}\\'', '--proxyusername \\'{{ az_devops_proxy_username }}\\'', '--proxypassword \\'{{ az_devops_proxy_password }}\\'']"
  when:
    - az_devops_proxy_url is defined
```

**Comment by sancfc** [comment]
I have exactly the same error, CentOS 8 and ansible 2.13.3 and you?

**Comment by mkoertgen** [comment]
Same for me. Looks like adding lists should be moved inside the `{{ }}`. At least according to the Jinja2 docs
- https://jinja.palletsprojects.com/en/3.0.x/templates/#math

However, this might also need native types as formulated here
- https://gist.github.com/mkrizek/dbcf415b485fc3f2d4b3676ce0013397

Digging deeper into this.

Ansible / Jinja2 is not really meant to be juggling with dynamic argument lists. Also there is lots of redundant duplications in the respective tasks (darwin, linux, windows).

**Comment by Al-thi** [comment]
A working configuration for proxy facts :
```yaml
 - name: Set proxy
  block:
    - name: Set proxy facts
      ansible.builtin.set_fact:
        agent_proxy_args:
          - "--proxyurl + '{{ az_devops_proxy_url }}'"
          - "--proxyusername + '{{ az_devops_proxy_username }}'"
          - "--proxypassword + '{{ az_devops_proxy_password }}'"
    - name: Append proxy configuration to agent commands
      ansible.builtin.set_fact:
        agent_cmd_args: "{{ agent_cmd_args + agent_proxy_args }}"
  when:
    - az_devops_proxy_url is not none
 ```
